# Generated by Django 4.2.29 on 2026-04-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Foodle SaaS Owner'), ('CAFE_OWNER', 'Tenant Admin'), ('MANAGER', 'Shift Manager'), ('CASHIER', 'Counter Person'), ('CHEF', 'Kitchen Staff')], default='CAFE_OWNER', max_length=32),
        ),
    ]
